<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class TPS extends CI_Controller
{
    function __construct()
    {

        parent::__construct();
        ceklogin();
        $this->load->model('Tps_model');
        $this->load->library('Form_validation');
    }

    public function index()
    {


        $data['tps_data'] = $this->db->get('tps')->result();
        $this->template->load('template/backend/dashboard', 'tps/tps_list', $data);
    }

    public function read($id)
    {
        $row = $this->Tps_model->get_by_id($id);
        if ($row) {
            $data = array(
                'id_tps' => $row->id_tps,
                'nama_tps' => $row->nama_tps,
                'lokasi' => $row->lokasi,

            );
            $this->template->load('template/backend/dashboard', 'tps/tps_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tps'));
        }
    }


    public function tambah()
    {

        // var_dump($data);
        // die;
        $data['kriteria'] =  $this->db->get('kriteria')->result_array();
        $this->_rules();



        if ($this->form_validation->run() == FALSE) {
            $this->template->load('template/backend/dashboard', 'tps/tambah', $data);
        } else {

            $data = array(
                'nama_tps' => $this->input->post('nama_tps', TRUE),
                'lokasi' => $this->input->post('lokasi', TRUE),

            );



            $this->db->insert('tps', $data);
            $this->session->set_flashdata('message', '<div class="alert alert-success" role="alert">Tambah Data Berhasil Berhasil
			</div>');
            redirect(site_url('tps'));
        }
    }

    public function update($id)
    {
        $row = $this->Tps_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Ubah',
                'action' => site_url('tps/update_action'),
                'id_tps' => set_value('id_tps', $row->id_tps),
                'nama_tps' => set_value('nama_tps', $row->nama_tps),
                'lokasi' => set_value('luas_lahan', $row->lokasi),

            );
            $this->template->load('template/backend/dashboard', 'tps/tps_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('tps'));
        }
    }

    public function update_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_tps', TRUE));
        } else {
            $data = array(
                'nama_tps' => $this->input->post('nama_tps', TRUE),
                'lokasi' => $this->input->post('lokasi', TRUE),
            );

            $this->Tps_model->update($this->input->post('id_tps', TRUE), $data);
            $this->session->set_flashdata('message', '<text class="alert alert-success"> Ubah Data TPS Berhasil</text>');
            redirect(site_url('tps'));
        }
    }

    public function delete($id)
    {
        $sql = $this->db->query("SELECT * FROM alternatif WHERE id_tps = '$id'")->num_rows();
        if ($sql > 0) {
            $this->session->set_flashdata('message', '<text class="alert alert-danger"> Data TPS masih terdaftar dalam alternatif!</text>');
            redirect(site_url('tps'));
        } else {

            $this->db->where('id_tps', $id);
            $this->db->delete('tps');
            $this->session->set_flashdata('message', '<text class="alert alert-success"> Hapus Data TPS Berhasil</text>');
            redirect(site_url('tps'));
        }
    }

    public function _rules()
    {
        $this->form_validation->set_rules('nama_tps', 'nama tps', 'trim|required');
        $this->form_validation->set_rules('lokasi', 'Lokasi', 'trim|required');

        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }
}

/* End of file Sekolah.php */
/* Location: ./application/controllers/Sekolah.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-07-23 05:12:40 */
/* http://harviacode.com */